name: Main Application CI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image Tag'
        required: false
        default: 'test'
  pull_request:
    types:
      - opened
      - synchronize
      - closed
      - reopened
    paths:
      - /**
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d.%H.%M')"

      - name: Get ECR Repository
        id: ecr
        run: echo "::set-output name=repository::op-main"

      - name: Get service name
        run: echo "::set-output name=service::Main"
        id: service_name

      - name: Extract branch name
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "branch=${GITHUB_BASE_REF}" >> $GITHUB_OUTPUT
          else
            echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          fi
        id: extract_branch

      - uses: actions/checkout@v2

      - name: Print Content
        run: |
          cat test.txt
        id: content
